### ISSUE TITLE
Bug in how Device() initialization handles name_or_file

### ISSUE THREAD

**Issue by otaku42** [otaku42/v4l2py#11]
https://github.com/otaku42/v4l2py/blob/b75d8cbea0375c6176f0fa7d43d5094bd10b9764/v4l2py/device.py#L639-L649

This does not make sense to me. The `elif` won't ever be hit, because `str` is already matched in the `if` part. Futhermore, even if the `elif` part would be hit it would fail, since `str` objects don't have attributes such as `name` or `mode`. 

I assume the intention of the last change (related to implementation of the GEvent stuff) was: behave as before if `name_or_file` is a string,  and behave different if a pathlib.Path is given. If that assumption is correct, it should probably be something like:
```python
        if isinstance(name_or_file, str)):
            filename = pathlib.Path(name_or_file)
            self._read_write = read_write
            self._fobj = None
        elif isinstance(name_or_file, pathlib.Path):
            filename = pathlib.Path(name_or_file.name)
            self._read_write = "+" in name_or_file.mode
            self._fobj = name_or_file
            # this object context manager won't close the file anymore
            self._context_level += 1
            self._init()
        else:
            ...
```
Although I'm not sure why in L640 a new `pathlib.Path` object get's instantiated out of the name attribute of an existing `pathlib.Path` object - instead we could simply use `filename = name_or_file` here, no?

Revisit later, submit a Draft-PR to upstream and see what @tiagocoutinho thinks of it.

**Comment by tiagocoutinho** [comment]
Thanks for bringing this to my attention.
The idea behind this was to be able to pass a path (str/Path) or a file object.
If you pass a file object the Device is no longer responsible for closing it. We do this by incrementing the _context_level so that when Device is used in a `with` statement it won't close the file when it exits 

The correct code should be:

```python
 if isinstance(name_or_file, (str, pathlib.Path)): 
     filename = pathlib.Path(name_or_file) 
     self._read_write = read_write 
     self._fobj = None 
 else: 
     filename = pathlib.Path(name_or_file.name) 
     self._read_write = "+" in name_or_file.mode 
     self._fobj = name_or_file 
     # this object context manager won't close the file anymore 
     self._context_level += 1 
     self._init() 
```

**Comment by otaku42** [comment]
Ok, I see. However, I suggest something like:
```python
 if isinstance(name_or_file, (str, pathlib.Path)): 
     filename = pathlib.Path(name_or_file) 
     self._read_write = read_write 
     self._fobj = None 
 elif isinstance(name_or_file, (io.IOBase, GEventIO)): 
     filename = pathlib.Path(name_or_file.name) 
     self._read_write = "+" in name_or_file.mode 
     self._fobj = name_or_file 
     # this object context manager won't close the file anymore 
     self._context_level += 1 
     self._init() 
else:
     raise TypeError(f"name_or_file must be str or a file-like object, not {name_or_file.__class__.__name__}")
```
I.e. using `elif` rather than `else` in that second path, as a safety rail to reduce the chance that accessing `name_or_file.name` and `name_or_file.mode` results in an exception. The list of classes to check for might need to be extended, though, and the imports would have to be adjusted accordingly.

What do you think?

**Comment by tiagocoutinho** [comment]
I like your suggestion.

But GeventIO is just a helper for handling io operations. I think that having:
`isinstance(name_of_file, io.IOBase)` is sufficient.

The GEventIO is supposed to be passed as argument to `io` parameter:

`dev = Device("/dev/video0', io=GeventIO)`
